[package]
name = "camloc-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pi"]
pi = []

[dependencies]
opencv = "0.77.0"

[profile.release]
strip = true
lto = true